# Generated by Django 4.2.2 on 2023-06-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
