# Generated by Django 4.2.2 on 2023-06-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_first_name_account_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.CharField(default='STB', max_length=100),
            preserve_default=False,
        ),
    ]
