# Generated by Django 4.2.2 on 2023-06-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
